version: '2'
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    user: root
    depends_on:
      - db
    ports:
      - "8000:8069"
      - "2000:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, unco>

      - /etc/odoo/custom/webkul_addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./filestore:/home/.local/share/Odoo/filestore
      - ./sessions:/home/.local/share/Odoo/sessions
    restart: always             # run as a service
